name: Push Build to Artifactory
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      # This action checks out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - run: |

          conan profile detect
          conan create . 

          conan remote add conan-dev-local https://soleng.jfrog.io/artifactory/conan-dev-local/
          conan remote login conan-dev-local sam -p ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          
          conan list --graph=create.json --graph-binaries=build --format=json > pkglist.json
          #conan upload --list=pkglist.json -r=conan-dev-local -c
          
          conan upload hello -r=conan-dev-local -c
